### PR TITLE
Draft: Attempt to use ProcessingChain for authproc filter invocation

### PR DESCRIPTION
**Pull request by pradtke**
Tested with preprodwarning for verifying being able to redirect user and then resume.

### CODE REVIEW

**Comment by pradtke** [comment]
@tvdijen I made some changes to `authoauth2` module to be able to invoke `authproc` filters using the ProcessingChain. When you have a moment could you take a look and let me know what you think?  OAuth2 doesn't have the equivalent of an `entityid` so I set those to either the `issuer` or the `authorize` endpoint for the `idp` metadata and to the oauth2 client id for the `sp` side metadata

**Comment by tvdijen** [comment]
It's looking pretty good Patrick! No remarks

**Comment by pradtke** [comment]
@tft7000 When you have some time could you test this branch that reuses the ProcessingChain for doing authproc filters?

**Comment by tft7000** [comment]
@pradtke : thank you! I will try to test the ProcessingChain next week.

**Comment by tft7000** [comment]
@pradtke : I tested it with my use case and it works perfectly! thanks very much. 
I also added the 4x times the preprodwarning module as additional step between my authproc filters and that worked as expected :-)
thank you for your time and work!

**Pull request merged**
